# Generated by Django 2.1.2 on 2018-10-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runningsteve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='runner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='runningsteve.Runner'),
        ),
        migrations.AlterField(
            model_name='race',
            name='terrain',
            field=models.IntegerField(choices=[(0, 'Road'), (1, 'Trail'), (2, 'Multi')], max_length=20, null=True, verbose_name='Terrain'),
        ),
    ]
