# Generated by Django 2.1.2 on 2019-03-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runningsteve', '0004_auto_20181014_2123'),
        ('runningsteve', '0004_auto_20181024_1634'),
    ]

    operations = [
    ]
